name: Python Tests

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            python/pyproject.toml
            python/requirements.txt
      - name: Install package
        run: pip install -e python
      - name: Run tests
        run: pytest -q
