name: Python Tests

on:
  push:
    paths:
      - 'python/**'
      - 'python/tests/test_tutorials.py'
      - '.github/workflows/python-tests.yml'
  pull_request:
    paths:
      - 'python/**'
      - 'python/tests/test_tutorials.py'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            python/pyproject.toml
            python/requirements.txt
      - name: Install package
        run: pip install -e "python[tests]" flake8 mypy pytest-cov nbval
      - name: Run tests
        run: pytest --cov=python/isetcam --cov-report=xml -q
      - name: Run notebook
        run: pytest --nbval notebooks/basic_pipeline.ipynb -q
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
      - name: Run flake8
        run: flake8 python/isetcam
      - name: Run mypy
        run: mypy python/isetcam
